<?php

namespace AlxDorosenco\CurlPhp\Tests\Unit\Traits;

use AlxDorosenco\CurlPhp\Traits\TCurlShareFunctions;
use PHPUnit\Framework\TestCase;

class TCurlShareFunctionsTest extends TestCase
{
    private $trait;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->trait = new class {
            use TCurlShareFunctions;

            public false|\CurlShareHandle $shareHandle;

            public function __construct(){
                $this->shareHandle = curl_share_init();
            }
        };
    }

    public function tearDown(): void
    {
        curl_share_close($this->trait->shareHandle);

        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public static function errorCodeConstantsProvider(): array
    {
        return [
            [CURLE_OK],
            [CURLE_UNSUPPORTED_PROTOCOL],
            [CURLE_FAILED_INIT],
            [CURLE_URL_MALFORMAT],
            [CURLE_COULDNT_RESOLVE_HOST],
            [CURLE_COULDNT_RESOLVE_PROXY]
        ];
    }

    public function testCloseMethod(): void
    {
        $this->expectNotToPerformAssertions();

        $this->trait->close();
    }

    public function testErrNoMethod(): void
    {
        $this->assertIsInt($this->trait->errNo());
    }

    public function testInitMethod(): void
    {
        $init = $this->trait->init();

        $this->assertIsObject($init);
        $this->assertSame(\CurlShareHandle::class, get_class($init));
    }

    public function testSetOptMethod(): void
    {
        $opt = $this->trait->setOpt(CURLSHOPT_SHARE, 1);

        $this->assertIsBool($opt);
    }

    /**
     * @dataProvider errorCodeConstantsProvider
     */
    public function testStrErrorMethod(int $value): void
    {
        $this->assertIsString($this->trait->strError($value));
    }
}